"""Book guide table change

Revision ID: 072813421057
Revises: 4a5d74bf9582
Create Date: 2025-01-27 21:19:46.713448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072813421057'
down_revision: Union[str, None] = '4a5d74bf9582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_guide', 'guest_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_guide', sa.Column('guest_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
