"""Tour attributes change

Revision ID: 09d291fef328
Revises: 6152baa9ba78
Create Date: 2025-02-04 20:27:10.587321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d291fef328'
down_revision: Union[str, None] = '6152baa9ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('destinations', sa.ARRAY(sa.Integer()), nullable=False))
    op.add_column('tours', sa.Column('departure_time', sa.Time(), nullable=False))
    op.add_column('tours', sa.Column('return_time', sa.Time(), nullable=False))
    op.add_column('tours', sa.Column('dress_code', sa.String(length=255), nullable=True))
    op.add_column('tours', sa.Column('not_included', sa.Text(), nullable=True))
    op.add_column('tours', sa.Column('included', sa.Text(), nullable=True))
    op.add_column('tours', sa.Column('photo_gallery', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint('tours_address_id_fkey', 'tours', type_='foreignkey')
    op.drop_column('tours', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tours_address_id_fkey', 'tours', 'addresses', ['address_id'], ['address_id'])
    op.alter_column('tours', 'duration',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tours', 'photo_gallery')
    op.drop_column('tours', 'included')
    op.drop_column('tours', 'not_included')
    op.drop_column('tours', 'dress_code')
    op.drop_column('tours', 'return_time')
    op.drop_column('tours', 'departure_time')
    op.drop_column('tours', 'destinations')
    # ### end Alembic commands ###
