"""review fixes

Revision ID: 1cd696d300ae
Revises: 93039e76289c
Create Date: 2025-02-05 15:42:20.090445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd696d300ae'
down_revision: Union[str, None] = '93039e76289c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_reviews',
    sa.Column('tour_review_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tour_review_id')
    )
    op.create_index(op.f('ix_tour_reviews_tour_review_id'), 'tour_reviews', ['tour_review_id'], unique=False)
    op.drop_column('resumes', 'rating')
    op.add_column('reviews', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.drop_constraint('reviews_guide_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'resumes', ['resume_id'], ['resume_id'])
    op.drop_column('reviews', 'guide_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('guide_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_guide_id_fkey', 'reviews', 'users', ['guide_id'], ['user_id'])
    op.drop_column('reviews', 'resume_id')
    op.add_column('resumes', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tour_reviews_tour_review_id'), table_name='tour_reviews')
    op.drop_table('tour_reviews')
    # ### end Alembic commands ###
