"""booking updates

Revision ID: 2cc400ec3d29
Revises: 27e90768b242
Create Date: 2025-02-24 14:34:42.744449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc400ec3d29'
down_revision: Union[str, None] = '27e90768b242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_guide', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('book_guide', sa.Column('language_id', sa.Integer(), nullable=False))
    op.add_column('book_guide', sa.Column('message', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'book_guide', 'languages', ['language_id'], ['language_id'])
    op.add_column('book_tour', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('book_tour', sa.Column('language_id', sa.Integer(), nullable=False))
    op.add_column('book_tour', sa.Column('message', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'book_tour', 'languages', ['language_id'], ['language_id'])
    op.drop_constraint('tour_reviews_tour_id_fkey', 'tour_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'tour_reviews', 'tours', ['tour_id'], ['tour_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tour_reviews', type_='foreignkey')
    op.create_foreign_key('tour_reviews_tour_id_fkey', 'tour_reviews', 'tours', ['tour_id'], ['tour_id'])
    op.drop_constraint(None, 'book_tour', type_='foreignkey')
    op.drop_column('book_tour', 'message')
    op.drop_column('book_tour', 'language_id')
    op.drop_column('book_tour', 'confirmed')
    op.drop_constraint(None, 'book_guide', type_='foreignkey')
    op.drop_column('book_guide', 'message')
    op.drop_column('book_guide', 'language_id')
    op.drop_column('book_guide', 'confirmed')
    # ### end Alembic commands ###
