"""created_at to reviews addition

Revision ID: 68b78d5e6879
Revises: eca6548b5c6f
Create Date: 2025-02-26 16:49:16.524528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b78d5e6879'
down_revision: Union[str, None] = 'eca6548b5c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tour_reviews', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_reviews', 'created_at')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
