"""Resume business logic attributes change

Revision ID: 8c6727c28d89
Revises: d20af5dc7255
Create Date: 2025-02-05 11:40:27.583819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6727c28d89'
down_revision: Union[str, None] = 'd20af5dc7255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_languages',
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], )
    )
    op.create_table('resume_addresses',
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], )
    )
    op.drop_column('resumes', 'languages')
    op.drop_column('resumes', 'addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('addresses', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('resume_addresses')
    op.drop_table('resume_languages')
    # ### end Alembic commands ###
