"""Resume price_type change

Revision ID: 93039e76289c
Revises: d1a810b709cf
Create Date: 2025-02-05 14:27:09.888887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93039e76289c'
down_revision: Union[str, None] = 'd1a810b709cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('price_type', sa.Text(), nullable=True))
    op.drop_column('resumes', 'payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('payment_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'price_type')
    # ### end Alembic commands ###
