"""review guide_id change

Revision ID: a970f4da7b8e
Revises: 1cd696d300ae
Create Date: 2025-02-05 16:06:32.711804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a970f4da7b8e'
down_revision: Union[str, None] = '1cd696d300ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('guide_id', sa.Integer(), nullable=False))
    op.drop_constraint('resumes_user_id_fkey', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['guide_id'], ['user_id'])
    op.drop_column('resumes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key('resumes_user_id_fkey', 'resumes', 'users', ['user_id'], ['user_id'])
    op.drop_column('resumes', 'guide_id')
    # ### end Alembic commands ###
