"""Resume attributes addition

Revision ID: d1a810b709cf
Revises: 8c6727c28d89
Create Date: 2025-02-05 14:16:50.337358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a810b709cf'
down_revision: Union[str, None] = '8c6727c28d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('payment_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'payment_type')
    op.drop_column('resumes', 'price')
    # ### end Alembic commands ###
