"""Tour attributes change 2

Revision ID: d20af5dc7255
Revises: 09d291fef328
Create Date: 2025-02-04 23:32:51.876941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd20af5dc7255'
down_revision: Union[str, None] = '09d291fef328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_languages',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.PrimaryKeyConstraint('tour_id', 'language_id')
    )
    op.create_table('tour_addresses',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.tour_id'], ),
    sa.PrimaryKeyConstraint('tour_id', 'address_id')
    )
    op.drop_column('tours', 'destinations')
    op.drop_column('tours', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('language', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tours', sa.Column('destinations', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_table('tour_addresses')
    op.drop_table('tour_languages')
    # ### end Alembic commands ###
