"""tour_date addition

Revision ID: eca6548b5c6f
Revises: 2cc400ec3d29
Create Date: 2025-02-24 19:08:15.356601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca6548b5c6f'
down_revision: Union[str, None] = '2cc400ec3d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_guide', sa.Column('tour_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_guide', 'tour_date')
    # ### end Alembic commands ###
